=== MacCloudGZ/XML/Midterms/ACT 4/Zabala_2H.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="UniversityScheduleSystem">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Courses">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Course" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="TITLE" type="xs:string" />
                                        <xs:element name="CreditValue" type="xs:string" />
                                        <xs:element name="Department" type="xs:string" />
                                        <xs:element name="ProfessorID" type="xs:string" />
                                    </xs:sequence>
                                    <xs:attribute name="CourseID" use="required" />
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Professors">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Professor" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Name" type="xs:string" />
                                        <xs:element name="Specialization" type="xs:string" />
                                    </xs:sequence>
                                    <xs:attribute name="ProfessorID" use="required" />
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Schedules">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Schedule" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="CourseID" type="xs:string" />
                                        <xs:element name="Professor">
                                            <xs:complexType>
                                                <xs:attribute name="ProfessorID" use="required" />
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="Timeslot" type="xs:string" />
                                        <xs:element name="RoomNumber" type="xs:string" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== MacCloudGZ/XML/ACT 4/Zabala_2H.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--vHeader?v-->
<UniversityScheduleSystem xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="Zabala_2H.xsd">
    
    <Courses>
       <Course CourseID="CD-102">
            <TITLE>LALA</TITLE>
            <CreditValue>102</CreditValue>
            <Department>CCS</Department>
            <ProfessorID>of100</ProfessorID>
        </Course>
        <Course CourseID="ALS-103">
            <TITLE>SEC ED</TITLE>
            <CreditValue>90</CreditValue>
            <Department>PE</Department>
            <ProfessorID>daw21</ProfessorID>
        </Course>
    </Courses>
    <Professors>
        <Professor ProfessorID="of100">
            <Name>VLADIMIR PUTIN</Name>
            <Specialization>NOT ETHICAL HACKING</Specialization>
        </Professor>
        <Professor ProfessorID="daw21">
            <Name>Vannessa Vlad</Name>
            <Specialization>Hot susy Bland</Specialization>
        </Professor>
    </Professors>
    <Schedules>
        <Schedule>
            <CourseID>CD-102</CourseID>
            <Professor ProfessorID="of100"/>
            <Timeslot>Monday 10:30AM-01:20PM</Timeslot>
            <RoomNumber>ACAD101</RoomNumber>
        </Schedule>
        <Schedule>
            <CourseID>ALS-103</CourseID>
            <Professor ProfessorID="daw21"/>
            <Timeslot></Timeslot>
            <RoomNumber></RoomNumber>
        </Schedule>
    </Schedules>
</UniversityScheduleSystem>
